///************************************************
/// Generated by: va
/// Date: 30/11/2015 05:22:45
/// Goal: Create User Service Class for DM_GIANG_VIEN
///************************************************
/// <summary>
/// Create User Service Class for DM_GIANG_VIEN
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_DM_GIANG_VIEN : US_Object
	{
		private const string c_TableName = "DM_GIANG_VIEN";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public string strMA_GIANG_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "MA_GIANG_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["MA_GIANG_VIEN"] = value;
			}
		}

		public bool IsMA_GIANG_VIENNull() 
		{
			return pm_objDR.IsNull("MA_GIANG_VIEN");
		}

		public void SetMA_GIANG_VIENNull() {
			pm_objDR["MA_GIANG_VIEN"] = System.Convert.DBNull;
		}

		public string strTEN_GIANG_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TEN_GIANG_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TEN_GIANG_VIEN"] = value;
			}
		}

		public bool IsTEN_GIANG_VIENNull() 
		{
			return pm_objDR.IsNull("TEN_GIANG_VIEN");
		}

		public void SetTEN_GIANG_VIENNull() {
			pm_objDR["TEN_GIANG_VIEN"] = System.Convert.DBNull;
		}

		public decimal dcID_KHOA_VIEN 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_KHOA_VIEN", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_KHOA_VIEN"] = value;
			}
		}

		public bool IsID_KHOA_VIENNull()	{
			return pm_objDR.IsNull("ID_KHOA_VIEN");
		}

		public void SetID_KHOA_VIENNull() {
			pm_objDR["ID_KHOA_VIEN"] = System.Convert.DBNull;
		}

		public string strSDT 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "SDT", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["SDT"] = value;
			}
		}

		public bool IsSDTNull() 
		{
			return pm_objDR.IsNull("SDT");
		}

		public void SetSDTNull() {
			pm_objDR["SDT"] = System.Convert.DBNull;
		}

		public string strQUE_QUAN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "QUE_QUAN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["QUE_QUAN"] = value;
			}
		}

		public bool IsQUE_QUANNull() 
		{
			return pm_objDR.IsNull("QUE_QUAN");
		}

		public void SetQUE_QUANNull() {
			pm_objDR["QUE_QUAN"] = System.Convert.DBNull;
		}

		public string strGIOI_TINH 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "GIOI_TINH", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["GIOI_TINH"] = value;
			}
		}

		public bool IsGIOI_TINHNull() 
		{
			return pm_objDR.IsNull("GIOI_TINH");
		}

		public void SetGIOI_TINHNull() {
			pm_objDR["GIOI_TINH"] = System.Convert.DBNull;
		}

		public DateTime datNGAY_SINH
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "NGAY_SINH", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["NGAY_SINH"] = value;
			}
		}

		public bool IsNGAY_SINHNull()
		{
			return pm_objDR.IsNull("NGAY_SINH");
		}

		public void SetNGAY_SINHNull()
		{
			pm_objDR["NGAY_SINH"] = System.Convert.DBNull;
		}

		public decimal dcTRANG_THAI_HSD 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "TRANG_THAI_HSD", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["TRANG_THAI_HSD"] = value;
			}
		}

		public bool IsTRANG_THAI_HSDNull()	{
			return pm_objDR.IsNull("TRANG_THAI_HSD");
		}

		public void SetTRANG_THAI_HSDNull() {
			pm_objDR["TRANG_THAI_HSD"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_DM_GIANG_VIEN() 
		{
			pm_objDS = new DS_DM_GIANG_VIEN();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DM_GIANG_VIEN(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DM_GIANG_VIEN(decimal i_dbID) 
		{
			pm_objDS = new DS_DM_GIANG_VIEN();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion


	}
}
