///************************************************
/// Generated by: tuandm
/// Date: 01/12/2015 09:28:05
/// Goal: Create User Service Class for DM_HOC_KY
///************************************************
/// <summary>
/// Create User Service Class for DM_HOC_KY
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_DM_HOC_KY : US_Object
	{
		private const string c_TableName = "DM_HOC_KY";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public string strMA_HOC_KY 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "MA_HOC_KY", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["MA_HOC_KY"] = value;
			}
		}

		public bool IsMA_HOC_KYNull() 
		{
			return pm_objDR.IsNull("MA_HOC_KY");
		}

		public void SetMA_HOC_KYNull() {
			pm_objDR["MA_HOC_KY"] = System.Convert.DBNull;
		}

		public decimal dcNAM_HOC_BAT_DAU 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "NAM_HOC_BAT_DAU", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["NAM_HOC_BAT_DAU"] = value;
			}
		}

		public bool IsNAM_HOC_BAT_DAUNull()	{
			return pm_objDR.IsNull("NAM_HOC_BAT_DAU");
		}

		public void SetNAM_HOC_BAT_DAUNull() {
			pm_objDR["NAM_HOC_BAT_DAU"] = System.Convert.DBNull;
		}

		public decimal dcNAM_HOC_KET_THUC 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "NAM_HOC_KET_THUC", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["NAM_HOC_KET_THUC"] = value;
			}
		}

		public bool IsNAM_HOC_KET_THUCNull()	{
			return pm_objDR.IsNull("NAM_HOC_KET_THUC");
		}

		public void SetNAM_HOC_KET_THUCNull() {
			pm_objDR["NAM_HOC_KET_THUC"] = System.Convert.DBNull;
		}

		public decimal dcTRANG_THAI_HSD 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "TRANG_THAI_HSD", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["TRANG_THAI_HSD"] = value;
			}
		}

		public bool IsTRANG_THAI_HSDNull()	{
			return pm_objDR.IsNull("TRANG_THAI_HSD");
		}

		public void SetTRANG_THAI_HSDNull() {
			pm_objDR["TRANG_THAI_HSD"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_DM_HOC_KY() 
		{
			pm_objDS = new DS_DM_HOC_KY();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DM_HOC_KY(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DM_HOC_KY(decimal i_dbID) 
		{
			pm_objDS = new DS_DM_HOC_KY();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion


	}
}
