///************************************************
/// Generated by: tuandm
/// Date: 28/11/2015 02:10:10
/// Goal: Create User Service Class for DM_LOP_SINH_VIEN
///************************************************
/// <summary>
/// Create User Service Class for DM_LOP_SINH_VIEN
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_DM_LOP_SINH_VIEN : US_Object
	{
		private const string c_TableName = "DM_LOP_SINH_VIEN";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public string strLOP_SINH_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "LOP_SINH_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["LOP_SINH_VIEN"] = value;
			}
		}

		public bool IsLOP_SINH_VIENNull() 
		{
			return pm_objDR.IsNull("LOP_SINH_VIEN");
		}

		public void SetLOP_SINH_VIENNull() {
			pm_objDR["LOP_SINH_VIEN"] = System.Convert.DBNull;
		}

		public decimal dcID_KHOA 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_KHOA", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_KHOA"] = value;
			}
		}

		public bool IsID_KHOANull()	{
			return pm_objDR.IsNull("ID_KHOA");
		}

		public void SetID_KHOANull() {
			pm_objDR["ID_KHOA"] = System.Convert.DBNull;
		}

		public decimal dcID_KHOA_VIEN 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_KHOA_VIEN", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_KHOA_VIEN"] = value;
			}
		}

		public bool IsID_KHOA_VIENNull()	{
			return pm_objDR.IsNull("ID_KHOA_VIEN");
		}

		public void SetID_KHOA_VIENNull() {
			pm_objDR["ID_KHOA_VIEN"] = System.Convert.DBNull;
		}

		public decimal dcTRANG_THAI_HSD 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "TRANG_THAI_HSD", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["TRANG_THAI_HSD"] = value;
			}
		}

		public bool IsTRANG_THAI_HSDNull()	{
			return pm_objDR.IsNull("TRANG_THAI_HSD");
		}

		public void SetTRANG_THAI_HSDNull() {
			pm_objDR["TRANG_THAI_HSD"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_DM_LOP_SINH_VIEN() 
		{
			pm_objDS = new DS_DM_LOP_SINH_VIEN();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DM_LOP_SINH_VIEN(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DM_LOP_SINH_VIEN(decimal i_dbID) 
		{
			pm_objDS = new DS_DM_LOP_SINH_VIEN();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion


	}
}
