///************************************************
/// Generated by: va
/// Date: 30/11/2015 04:04:52
/// Goal: Create User Service Class for DM_KHOA_VIEN
///************************************************
/// <summary>
/// Create User Service Class for DM_KHOA_VIEN
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_DM_KHOA_VIEN : US_Object
	{
		private const string c_TableName = "DM_KHOA_VIEN";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public string strMA_KHOA_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "MA_KHOA_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["MA_KHOA_VIEN"] = value;
			}
		}

		public bool IsMA_KHOA_VIENNull() 
		{
			return pm_objDR.IsNull("MA_KHOA_VIEN");
		}

		public void SetMA_KHOA_VIENNull() {
			pm_objDR["MA_KHOA_VIEN"] = System.Convert.DBNull;
		}

		public string strTEN_KHOA_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TEN_KHOA_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TEN_KHOA_VIEN"] = value;
			}
		}

		public bool IsTEN_KHOA_VIENNull() 
		{
			return pm_objDR.IsNull("TEN_KHOA_VIEN");
		}

		public void SetTEN_KHOA_VIENNull() {
			pm_objDR["TEN_KHOA_VIEN"] = System.Convert.DBNull;
		}

		public decimal dcPHAN_LOAI 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "PHAN_LOAI", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["PHAN_LOAI"] = value;
			}
		}

		public bool IsPHAN_LOAINull()	{
			return pm_objDR.IsNull("PHAN_LOAI");
		}

		public void SetPHAN_LOAINull() {
			pm_objDR["PHAN_LOAI"] = System.Convert.DBNull;
		}

		public decimal dcTRANG_THAI_HSD 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "TRANG_THAI_HSD", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["TRANG_THAI_HSD"] = value;
			}
		}

		public bool IsTRANG_THAI_HSDNull()	{
			return pm_objDR.IsNull("TRANG_THAI_HSD");
		}

		public void SetTRANG_THAI_HSDNull() {
			pm_objDR["TRANG_THAI_HSD"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_DM_KHOA_VIEN() 
		{
			pm_objDS = new DS_DM_KHOA_VIEN();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DM_KHOA_VIEN(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DM_KHOA_VIEN(decimal i_dbID) 
		{
			pm_objDS = new DS_DM_KHOA_VIEN();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion


	}
}
