///************************************************
/// Generated by: tuandm
/// Date: 03/12/2015 06:58:46
/// Goal: Create User Service Class for V_SINH_VIEN_GPA
///************************************************
/// <summary>
/// Create User Service Class for V_SINH_VIEN_GPA
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_V_SINH_VIEN_GPA : US_Object
	{
		private const string c_TableName = "V_SINH_VIEN_GPA";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public decimal dcID_SINH_VIEN 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_SINH_VIEN", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_SINH_VIEN"] = value;
			}
		}

		public bool IsID_SINH_VIENNull()	{
			return pm_objDR.IsNull("ID_SINH_VIEN");
		}

		public void SetID_SINH_VIENNull() {
			pm_objDR["ID_SINH_VIEN"] = System.Convert.DBNull;
		}

		public string strMA_SINH_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "MA_SINH_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["MA_SINH_VIEN"] = value;
			}
		}

		public bool IsMA_SINH_VIENNull() 
		{
			return pm_objDR.IsNull("MA_SINH_VIEN");
		}

		public void SetMA_SINH_VIENNull() {
			pm_objDR["MA_SINH_VIEN"] = System.Convert.DBNull;
		}

		public string strTEN_SINH_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TEN_SINH_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TEN_SINH_VIEN"] = value;
			}
		}

		public bool IsTEN_SINH_VIENNull() 
		{
			return pm_objDR.IsNull("TEN_SINH_VIEN");
		}

		public void SetTEN_SINH_VIENNull() {
			pm_objDR["TEN_SINH_VIEN"] = System.Convert.DBNull;
		}

		public decimal dcID_LOP_SINH_VIEN 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_LOP_SINH_VIEN", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_LOP_SINH_VIEN"] = value;
			}
		}

		public bool IsID_LOP_SINH_VIENNull()	{
			return pm_objDR.IsNull("ID_LOP_SINH_VIEN");
		}

		public void SetID_LOP_SINH_VIENNull() {
			pm_objDR["ID_LOP_SINH_VIEN"] = System.Convert.DBNull;
		}

		public string strLOP_SINH_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "LOP_SINH_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["LOP_SINH_VIEN"] = value;
			}
		}

		public bool IsLOP_SINH_VIENNull() 
		{
			return pm_objDR.IsNull("LOP_SINH_VIEN");
		}

		public void SetLOP_SINH_VIENNull() {
			pm_objDR["LOP_SINH_VIEN"] = System.Convert.DBNull;
		}

		public decimal dcID_KHOA 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_KHOA", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_KHOA"] = value;
			}
		}

		public bool IsID_KHOANull()	{
			return pm_objDR.IsNull("ID_KHOA");
		}

		public void SetID_KHOANull() {
			pm_objDR["ID_KHOA"] = System.Convert.DBNull;
		}

		public string strKHOA 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "KHOA", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["KHOA"] = value;
			}
		}

		public bool IsKHOANull() 
		{
			return pm_objDR.IsNull("KHOA");
		}

		public void SetKHOANull() {
			pm_objDR["KHOA"] = System.Convert.DBNull;
		}

		public decimal dcTRANG_THAI_HSD 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "TRANG_THAI_HSD", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["TRANG_THAI_HSD"] = value;
			}
		}

		public bool IsTRANG_THAI_HSDNull()	{
			return pm_objDR.IsNull("TRANG_THAI_HSD");
		}

		public void SetTRANG_THAI_HSDNull() {
			pm_objDR["TRANG_THAI_HSD"] = System.Convert.DBNull;
		}

		public decimal dcID_KHOA_VIEN 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_KHOA_VIEN", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_KHOA_VIEN"] = value;
			}
		}

		public bool IsID_KHOA_VIENNull()	{
			return pm_objDR.IsNull("ID_KHOA_VIEN");
		}

		public void SetID_KHOA_VIENNull() {
			pm_objDR["ID_KHOA_VIEN"] = System.Convert.DBNull;
		}

		public string strMA_KHOA_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "MA_KHOA_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["MA_KHOA_VIEN"] = value;
			}
		}

		public bool IsMA_KHOA_VIENNull() 
		{
			return pm_objDR.IsNull("MA_KHOA_VIEN");
		}

		public void SetMA_KHOA_VIENNull() {
			pm_objDR["MA_KHOA_VIEN"] = System.Convert.DBNull;
		}

		public string strTEN_KHOA_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TEN_KHOA_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TEN_KHOA_VIEN"] = value;
			}
		}

		public bool IsTEN_KHOA_VIENNull() 
		{
			return pm_objDR.IsNull("TEN_KHOA_VIEN");
		}

		public void SetTEN_KHOA_VIENNull() {
			pm_objDR["TEN_KHOA_VIEN"] = System.Convert.DBNull;
		}

		public decimal dcExpr1 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "Expr1", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["Expr1"] = value;
			}
		}

		public bool IsExpr1Null()	{
			return pm_objDR.IsNull("Expr1");
		}

		public void SetExpr1Null() {
			pm_objDR["Expr1"] = System.Convert.DBNull;
		}

		public decimal dcExpr2 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "Expr2", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["Expr2"] = value;
			}
		}

		public bool IsExpr2Null()	{
			return pm_objDR.IsNull("Expr2");
		}

		public void SetExpr2Null() {
			pm_objDR["Expr2"] = System.Convert.DBNull;
		}

		public string strGIOI_TINH 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "GIOI_TINH", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["GIOI_TINH"] = value;
			}
		}

		public bool IsGIOI_TINHNull() 
		{
			return pm_objDR.IsNull("GIOI_TINH");
		}

		public void SetGIOI_TINHNull() {
			pm_objDR["GIOI_TINH"] = System.Convert.DBNull;
		}

		public DateTime datNGAY_SINH
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "NGAY_SINH", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["NGAY_SINH"] = value;
			}
		}

		public bool IsNGAY_SINHNull()
		{
			return pm_objDR.IsNull("NGAY_SINH");
		}

		public void SetNGAY_SINHNull()
		{
			pm_objDR["NGAY_SINH"] = System.Convert.DBNull;
		}

		public string strQUE_QUAN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "QUE_QUAN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["QUE_QUAN"] = value;
			}
		}

		public bool IsQUE_QUANNull() 
		{
			return pm_objDR.IsNull("QUE_QUAN");
		}

		public void SetQUE_QUANNull() {
			pm_objDR["QUE_QUAN"] = System.Convert.DBNull;
		}

		public string strSDT 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "SDT", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["SDT"] = value;
			}
		}

		public bool IsSDTNull() 
		{
			return pm_objDR.IsNull("SDT");
		}

		public void SetSDTNull() {
			pm_objDR["SDT"] = System.Convert.DBNull;
		}

		public decimal dcTRANG_THAI 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "TRANG_THAI", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["TRANG_THAI"] = value;
			}
		}

		public bool IsTRANG_THAINull()	{
			return pm_objDR.IsNull("TRANG_THAI");
		}

		public void SetTRANG_THAINull() {
			pm_objDR["TRANG_THAI"] = System.Convert.DBNull;
		}

		public decimal dcExpr3 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "Expr3", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["Expr3"] = value;
			}
		}

		public bool IsExpr3Null()	{
			return pm_objDR.IsNull("Expr3");
		}

		public void SetExpr3Null() {
			pm_objDR["Expr3"] = System.Convert.DBNull;
		}

		public decimal dcID_HOC_KY 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_HOC_KY", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_HOC_KY"] = value;
			}
		}

		public bool IsID_HOC_KYNull()	{
			return pm_objDR.IsNull("ID_HOC_KY");
		}

		public void SetID_HOC_KYNull() {
			pm_objDR["ID_HOC_KY"] = System.Convert.DBNull;
		}

		public string strMA_HOC_KY 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "MA_HOC_KY", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["MA_HOC_KY"] = value;
			}
		}

		public bool IsMA_HOC_KYNull() 
		{
			return pm_objDR.IsNull("MA_HOC_KY");
		}

		public void SetMA_HOC_KYNull() {
			pm_objDR["MA_HOC_KY"] = System.Convert.DBNull;
		}

		public decimal dcExpr5 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "Expr5", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["Expr5"] = value;
			}
		}

		public bool IsExpr5Null()	{
			return pm_objDR.IsNull("Expr5");
		}

		public void SetExpr5Null() {
			pm_objDR["Expr5"] = System.Convert.DBNull;
		}

		public decimal dcGPA 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "GPA", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["GPA"] = value;
			}
		}

		public bool IsGPANull()	{
			return pm_objDR.IsNull("GPA");
		}

		public void SetGPANull() {
			pm_objDR["GPA"] = System.Convert.DBNull;
		}

		public decimal dcCPA 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "CPA", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["CPA"] = value;
			}
		}

		public bool IsCPANull()	{
			return pm_objDR.IsNull("CPA");
		}

		public void SetCPANull() {
			pm_objDR["CPA"] = System.Convert.DBNull;
		}

		public string strTEN_TRANG_THAI 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TEN_TRANG_THAI", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TEN_TRANG_THAI"] = value;
			}
		}

		public bool IsTEN_TRANG_THAINull() 
		{
			return pm_objDR.IsNull("TEN_TRANG_THAI");
		}

		public void SetTEN_TRANG_THAINull() {
			pm_objDR["TEN_TRANG_THAI"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_V_SINH_VIEN_GPA() 
		{
			pm_objDS = new DS_V_SINH_VIEN_GPA();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_V_SINH_VIEN_GPA(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_V_SINH_VIEN_GPA(decimal i_dbID) 
		{
			pm_objDS = new DS_V_SINH_VIEN_GPA();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion


	}
}
